package by.academy.it.service;

/**
 * This class contain string constants for Services.
 */
class Constants {

    static final String USER = "user";
    static final String USERS = "users";
    static final String CURRENT_URI = "currentURI";
    static final String MAIN = "/main/";
    static final String PATH = "/WEB-INF/jsp/";
    static final String JSP = ".jsp";
    static final String RESULT = "result";
    static final String SUCCESS = "SUCCESS";
    static final String FAILURE = "FAILURE";
    static final String ERROR_MESSAGE = "errorMessage";
    static final String ERROR = "/main/error";
    static final String MATCH_EXCEPTION = "match.exception";
    static final String LANG = "lang";
    static final String LOGIN = "login";
    static final String PASSWORD = "password";
    static final String HOME = "/main/home";
    static final String LOGIN_FAILURE = "login.failure";
    static final String MESSAGE = "message";
    static final String INCORRECT_PASSWORD = "password.incorrect";
    static final String LOGIN_EXCEPTION = "login.exception";
    static final String MATCH = "match";
    static final String MATCH_ID = "matchId";
    static final String MATCH_ID_ERROR = "match.id.error";
    static final String MAIN_BET = "/main/bet";
    static final String FIRST_NAME = "firstName";
    static final String LAST_NAME = "lastName";
    static final String EMAIL = "email";
    static final String REGISTRATION_ERROR = "registration.error";
    static final String MATCHES = "matches";
    static final String MATCHES_LIST = "matchesList";
    static final String MATCHES_LIST_EMPTY = "matches.list.empty";
    static final String MATCHES_MESSAGE = "matchesMessage";
    static final String PAGE_ERROR = "page.error";
    static final String PAGE = "page";
    static final String CURRENT_PAGE = "currentPage";
    static final String PAGES = "pages";
    static final String BET = "bet";
    static final String AMOUNT = "amount";
    static final String BET_PARAM_ERROR = "bet.param.error";
    static final String BET_ERROR = "bet.error";
    static final String NOT_ENOUGH = "NOT_ENOUGH";
    static final String KEY = "key";
    static final String AMOUNT_ERROR = "amount.error";
    static final String TOPUP_ERROR = "top.up.error";
    static final String CONFIRM_MESSAGE = "confirmMessage";
    static final String BETS_EXCEPTION = "bets.error";
    static final String BETS = "bets";
    static final String FINISH_ERROR = "finish.error";
    static final String NUMBER_ERROR = "number.error";
    static final String FIRST_WON = "1";
    static final String SECOND_WON = "2";
    static final String DRAW = "X";
    static final String NO_USERS_ERROR = "no.users.error";
    static final String USERS_ERROR = "users.error";
    static final String BALANCE = "balance";
    static final String ROLE = "role";
    static final String CREATE_USER_ERROR = "create.user.error";
    static final String UPDATE_USER = "update-user";
    static final String SHOW_UPDATE_USER_ERROR = "show.update.user.error";
    static final String SHOW_UPDATE_USER_PARAMETER_ERROR = "show.update.user.parameter.error";
    static final String ID = "id";
    static final String USER_MESSAGE = "userMessage";
    static final String CREATE_USER_MESSAGE = "create.user.message";
    static final String UPDATE_USER_MESSAGE = "update.user.message";
    static final String DELETE_USER_ERROR = "delete.user.error";
    static final String DELETE_USER_MESSAGE = "delete.user.message";
    static final String WON = "won";
    static final String LOST = "lost";
    static final String USER_NOT_FOUND = "user.not.found";
    static final String DELETE_YOURSELF_MESSAGE = "delete.yourself.message";
    static final String ROLES_ERROR = "roles.error";
    static final String ROLES = "roles";
    static final String NO_ROLES_ERROR = "no.roles.error";
    static final String ROLE_ERROR = "role.error";
    static final String ROLE_DATA_ERROR = "role.data.error";
    static final String CREATE_ROLE_MESSAGE = "create.role.message";
    static final String UPDATED_USER = "updateUser";
    static final String UPDATED_ROLE = "updateRole";
    static final String UPDATE_ROLE = "update-role";
    static final String ROLE_MESSAGE = "roleMessage";
    static final String ROLE_NOT_FOUND = "role.not.found";
    static final String SHOW_UPDATE_ROLE_ERROR = "show.update.role.error";
    static final String SHOW_UPDATE_ROLE_PARAMETER_ERROR = "show.update.role.parameter.error";
    static final String UPDATE_ROLE_MESSAGE = "update.role.message";
    static final String UPDATE_ROLE_ERROR = "update.role.error";
    static final String UPDATE_FORBIDDEN = "update.forbidden";
    static final String DELETE_FORBIDDEN = "delete.forbidden";
    static final String DELETE_ROLE_MESSAGE = "delete.role.message";
    static final String DELETE_ROLE_ERROR = "delete.role.error";

}
